servicemesh-es/servicemesh.es

- _includes/comparison.html
* Clarify Vault is an optional CA in Consul.
* Remove Consul as a platform (it does not host workloads). Add VMs.
* Remove Consul and Nomad from Istio's list of supported platforms.
* Fix HashiCorp casing
> Update Consul column

- _includes/comparison.html
This PR:
- Updates Maesh version
- Provides some missing Maesh features
- Fixes Containous casing
ping @mmatur @santode for review/corrections
> Update Maesh column

- _includes/comparison.html
- Update column for Consul's retry/timeout support
- Change URL for Consul mTLS
> Update Consul retry/timeout support

- _includes/comparison.html
Update column to reflect the circuit breaking support which was added in Consul version 1.7.0.
> Update Consul circuit breaking

- _includes/comparison.html
https://github.com/Kong/kuma/issues/548
> Kuma grpc load balancing not support

- _includes/comparison.html
Fixing some inaccuracies to reflect the latest state of Kuma. I will publish soon a list of Kuma adopters so that we can also remove the line that Kuma is not production ready.
> docs(kuma): updating to latest Kuma version

- _includes/comparison.html
It seems to be incorrect.
https://istio.io/latest/docs/concepts/traffic-management/#load-balancing-options
Thank you for the useful document anyway.
> Fix Istio's load balancing model

- _includes/implementations.html
The two sentences were begging to be combined 😄
> Cleanup of sentences in implementations.html

- _includes/comparison.html
This commit updates the Consul version to 1.9, updates the list of supported features, and changes Consul URLs to point to updated locations.
> Update Consul version and supported features

- _includes/comparison.html
> "unofficial/3rd party support" annotations about Service Mesh Interface compatibility

- _includes/comparison.html
Some changes to reflect the current state of play with Open Service Mesh
> update to reflect Open Service Mesh as of 0.82

- _includes/comparison.html
Updating to latest version of Kuma which ships with out of the box Grafana dashboard for golden signal visualization, and visual reports in the GUI on the state of the service mesh across multiple zones.
> docs(kuma): updating to latest version

- _includes/comparison.html
- _includes/implementations.html
Hi! I noticed some inaccuracies in the entry for OSM, and fixed a couple of SMI-description typos while I was making a PR anyhow. Thanks!
Signed-off-by: Bridget Kromhout <bridget@kromhout.org>
> Updates OSM details and fixes SMI typos.

- _includes/comparison.html
Update Consul version to 1.10 as well as the list of supported features, and associated doc links.
> Updated Consul version to 1.10

- _includes/comparison.html
Some updates from what I've gleaned from the release notes and slack
> linkerd 2.11 updates

- _includes/comparison.html
- _includes/implementations.html
- Add link Consul case studies under production usage.
- Add link to distributed tracing setup instructions.
- Update several URL paths.
- Correct 'mTLS by default' and 'mTLS permissive mode' columns.
- Call out support for Kubernetes Gateway API with Consul API Gateway.
> Update Consul content

- _includes/comparison.html
- _includes/implementations.html
Signed-off-by: Charly Molter <charly.molter@konghq.com>
> refresh Kuma information

- _includes/comparison.html
https://release-v1-1.docs.openservicemesh.io/docs/guides/traffic_management/circuit_breaking/
> Adding OMS Circuit Breaking Support

- _includes/comparison.html
Adding and updating the latest information for Kuma mesh :)
Signed-off-by: John Harris <john@johnharris.io>
> Update Kuma (08/22)

- _includes/comparison.html
- Bump to version 1.14.0
- Link to Cluster Peering
> Update Consul for 1.14.0

- _includes/comparison.html
> Consul 1.16 - Update comparison.html

- _includes/comparison.html
Updates after releasing Linkerd 2.13
Signed-off-by: Flynn <flynn@buoyant.io>
> Updates for Linkerd

- _includes/comparison.html
- _includes/implementations.html
Update the table/s to reflect the [archival of OpenServiceMesh](https://openservicemesh.io/blog/osm-project-update/) and the [graduation of Istio](https://istio.io/blog/2023/istio-graduates-within-cncf/).
> Changes for Istio and OpenServiceMesh

- _includes/comparison.html
- Added new version
- Updated Fault injection section
> consul: Update for 1.18.x release
